export type NormalizedLanguage = string

export const PLAIN_TEXT_LANGUAGES = new Set(['text', 'txt', 'plain', 'plaintext'])

const SUPPORTED_LANGUAGES = new Set([
  'html',
  'xml',
  'css',
  'scss',
  'sass',
  'less',
  'postcss',
  'javascript',
  'jsx',
  'typescript',
  'tsx',
  'vue',
  'svelte',
  'astro',
  'angular-html',
  'angular-ts',
  'mdx',
  'python',
  'go',
  'rust',
  'java',
  'kotlin',
  'scala',
  'c',
  'cpp',
  'csharp',
  'fsharp',
  'swift',
  'objective-c',
  'objective-cpp',
  'php',
  'ruby',
  'perl',
  'lua',
  'dart',
  'elixir',
  'erlang',
  'clojure',
  'haskell',
  'ocaml',
  'zig',
  'nim',
  'crystal',
  'v',
  'vala',
  'pascal',
  'fortran-free-form',
  'bash',
  'fish',
  'powershell',
  'batch',
  'docker',
  'make',
  'cmake',
  'nginx',
  'apache',
  'terraform',
  'hcl',
  'bicep',
  'nix',
  'puppet',
  'ssh-config',
  'dotenv',
  'ini',
  'properties',
  'json',
  'jsonc',
  'json5',
  'jsonl',
  'yaml',
  'toml',
  'csv',
  'graphql',
  'protobuf',
  'http',
  'prisma',
  'sql',
  'plsql',
  'kusto',
  'cypher',
  'sparql',
  'markdown',
  'asciidoc',
  'rst',
  'latex',
  'bibtex',
  'typst',
  'mermaid',
  'qml',
  'vb',
  'asm',
  'wasm',
  'verilog',
  'system-verilog',
  'vhdl',
  'glsl',
  'hlsl',
  'wgsl',
  'shaderlab',
  'r',
  'julia',
  'matlab',
  'wolfram',
  'scheme',
  'racket',
  'lisp',
  'common-lisp',
  'prolog',
  'coq',
  'lean',
  'elm',
  'purescript',
  'fennel',
  'solidity',
  'vyper',
  'move',
  'cadence',
  'clarity',
  'diff',
  'git-commit',
  'git-rebase',
  'log',
  'ansi',
  'regexp',
])

const LANGUAGE_ALIASES: Record<string, string> = {
  ts: 'typescript',
  mts: 'typescript',
  cts: 'typescript',
  js: 'javascript',
  mjs: 'javascript',
  cjs: 'javascript',
  py: 'python',
  python3: 'python',
  rb: 'ruby',
  rs: 'rust',
  kt: 'kotlin',
  kts: 'kotlin',
  erl: 'erlang',
  clj: 'clojure',
  hs: 'haskell',
  jl: 'julia',
  cs: 'csharp',
  fs: 'fsharp',
  'c++': 'cpp',
  hpp: 'cpp',
  objc: 'objective-c',
  'obj-c': 'objective-c',
  objectivec: 'objective-c',
  f: 'fortran-free-form',
  f03: 'fortran-free-form',
  f08: 'fortran-free-form',
  f18: 'fortran-free-form',
  f90: 'fortran-free-form',
  f95: 'fortran-free-form',
  shell: 'bash',
  shellscript: 'bash',
  sh: 'bash',
  zsh: 'bash',
  ksh: 'bash',
  ps: 'powershell',
  ps1: 'powershell',
  pwsh: 'powershell',
  bat: 'batch',
  cmd: 'batch',
  dockerfile: 'docker',
  makefile: 'make',
  mk: 'make',
  tf: 'terraform',
  tfvars: 'terraform',
  env: 'dotenv',
  htm: 'html',
  xhtml: 'html',
  yml: 'yaml',
  md: 'markdown',
  adoc: 'asciidoc',
  tex: 'latex',
  typ: 'typst',
  gql: 'graphql',
  proto: 'protobuf',
  postgres: 'sql',
  postgresql: 'sql',
  mysql: 'sql',
  sqlite: 'sql',
  kql: 'kusto',
  patch: 'diff',
  systemverilog: 'system-verilog',
  sv: 'system-verilog',
  wat: 'wasm',
  mathematica: 'wolfram',
  wl: 'wolfram',
  regex: 'regexp',
}

export function normalizeLanguage(lang?: string): NormalizedLanguage | undefined {
  const raw = lang?.trim().toLowerCase()
  if (!raw) return undefined

  const first = raw.split(/[\s,{[]/, 1)[0]
  if (!first) return undefined
  if (PLAIN_TEXT_LANGUAGES.has(first)) return 'text'

  const normalized = LANGUAGE_ALIASES[first] ?? first
  if (PLAIN_TEXT_LANGUAGES.has(normalized)) return 'text'
  if (SUPPORTED_LANGUAGES.has(normalized)) return normalized
  return undefined
}
